### ISSUE TITLE
Question about SRCSET

### ISSUE THREAD

**Issue by jimgit** [thomhines/square1#3]
Could you explain this line on the main page:

Note: Appending data- to the 'src' and **'srcset'** attributes will enable async loading (eg. data-src="image1.png").

What is the srcset?

Is adding data-src sufficent to get lazy loading to work?

**Comment by thomhines** [comment]
'srcset' is a convenient way to build in responsive images that loads different image files depending on the screen resolution. Check it out here: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

To answer your second question, yes, using either data-src or data-srcset alone will trigger the lazy loading functionality.
