### ISSUE TITLE
If you passed a string number it will redefine the slider 

### ISSUE THREAD

**Issue by Tarek-Adra** [thomhines/square1#5]
$('.slideshow').square1('2'); // cause recreation the slider 

can you add an exception for converting to number like parseInt() 
or just add notice that in your documentation must be a number

**Comment by thomhines** [comment]
Good point! I'll take care of this soon. Thanks for bringing it to my attention!

**Comment by thomhines** [comment]
I finally got around to updating and testing this. Let me know if you run into any problems with the new code. Thank you again for the suggestion!
